'use client';
import { FormEvent, useEffect, useState } from 'react';
import { API_URL } from '../../../lib/api';
type Store = { id:string; name:string };
export default function WhatsappAdminPage(){
 const [token,setToken]=useState(''); const [stores,setStores]=useState<Store[]>([]); const [storeId,setStoreId]=useState('');
 const [form,setForm]=useState({whatsapp:'',whatsappEnabled:true,whatsappMessageTemplate:''}); const [message,setMessage]=useState('');
 useEffect(()=>setToken(localStorage.getItem('menu-commerce-token')??''),[]);
 async function request(path:string,options:RequestInit={}){const r=await fetch(`${API_URL}${path}`,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...(options.headers??{})}});const d=await r.json();if(!r.ok)throw new Error(Array.isArray(d.message)?d.message.join(', '):d.message);return d;}
 async function load(){try{const data=await request('/admin/stores');setStores(data);if(data[0]){setStoreId(data[0].id);await loadConfig(data[0].id)}}catch(e){setMessage(e instanceof Error?e.message:'Erro.')}}
 async function loadConfig(id=storeId){const d=await request(`/admin/stores/${id}/whatsapp`);setForm({whatsapp:d.whatsapp??'',whatsappEnabled:d.whatsappEnabled,whatsappMessageTemplate:d.whatsappMessageTemplate??''});}
 async function save(e:FormEvent){e.preventDefault();try{await request(`/admin/stores/${storeId}/whatsapp`,{method:'PATCH',body:JSON.stringify(form)});setMessage('Configuração salva.')}catch(err){setMessage(err instanceof Error?err.message:'Erro.')}}
 return <main className="admin-shell"><div className="admin-top"><div><span className="version">v0.7.0</span><h1>WhatsApp</h1></div><div className="header-actions"><a href="/admin">Catálogo</a><a href="/admin/pedidos">Pedidos</a><a href="/">Cardápio</a></div></div>
 {!token?<section className="card"><p>Faça login no painel administrativo antes de configurar o WhatsApp.</p><a href="/admin">Ir para o login</a></section>:<section className="card"><div className="toolbar"><h2>Configuração da loja</h2><button onClick={load}>Carregar lojas</button></div>{stores.length>0&&<select value={storeId} onChange={async e=>{setStoreId(e.target.value);await loadConfig(e.target.value)}}>{stores.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select>}<form onSubmit={save}><label>Número com DDI e DDD<input value={form.whatsapp} onChange={e=>setForm({...form,whatsapp:e.target.value})} placeholder="5512999999999" /></label><label className="check"><input type="checkbox" checked={form.whatsappEnabled} onChange={e=>setForm({...form,whatsappEnabled:e.target.checked})}/> Habilitar envio pelo WhatsApp</label><label>Modelo da mensagem<textarea rows={14} value={form.whatsappMessageTemplate} onChange={e=>setForm({...form,whatsappMessageTemplate:e.target.value})} placeholder="Deixe vazio para usar o modelo padrão." /></label><p>Variáveis: {'{{orderNumber}}'}, {'{{customerName}}'}, {'{{serviceType}}'}, {'{{items}}'}, {'{{subtotal}}'}, {'{{deliveryFee}}'}, {'{{discount}}'}, {'{{total}}'}, {'{{address}}'}, {'{{notes}}'}.</p><button disabled={!storeId}>Salvar configuração</button></form><p className="message">{message}</p></section>}</main>;
}
