'use client';
import { useEffect, useState } from 'react';
import { API_URL, money } from '../../../lib/api';
type Order={id:string;orderNumber:string;status:string;serviceType:string;total:string;createdAt:string;customer:{name:string;phone:string};items:{quantity:number}[]};
const statuses=['RECEIVED','CONFIRMED','PREPARING','READY','OUT_FOR_DELIVERY','DELIVERED','CANCELLED'];
const labels:Record<string,string>={RECEIVED:'Recebido',CONFIRMED:'Confirmado',PREPARING:'Em preparação',READY:'Pronto',OUT_FOR_DELIVERY:'Saiu para entrega',DELIVERED:'Entregue',CANCELLED:'Cancelado'};
export default function OrdersAdmin(){const [orders,setOrders]=useState<Order[]>([]);const [message,setMessage]=useState('');const [token,setToken]=useState('');
 async function load(){const r=await fetch(`${API_URL}/admin/orders`,{headers:{Authorization:`Bearer ${token}`}});const d=await r.json();if(!r.ok)throw new Error(d.message??'Falha ao carregar.');setOrders(d)}
 useEffect(()=>{const saved=localStorage.getItem('menu-commerce-token')??'';setToken(saved);if(saved) fetch(`${API_URL}/admin/orders`,{headers:{Authorization:`Bearer ${saved}`}}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.message??'Falha ao carregar.');return d}).then(setOrders).catch(e=>setMessage(e.message));else setMessage('Entre no painel administrativo antes de acessar os pedidos.')},[]);
 async function update(id:string,status:string){const r=await fetch(`${API_URL}/admin/orders/${id}/status`,{method:'PATCH',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({status})});if(!r.ok){const d=await r.json();setMessage(d.message??'Erro.');return}await load();setMessage('Status atualizado.')}
 return <main className="admin-shell"><div className="admin-top"><div><span className="version">v0.5.0</span><h1>Operação de pedidos</h1></div><div className="header-actions"><a href="/admin">Catálogo</a><a href="/admin/promocoes">Promoções</a><a href="/">Cardápio</a></div></div><p className="message">{message}</p><section className="orders-board">{orders.map(o=><article className="card order-card" key={o.id}><div className="toolbar"><div><strong>#{o.orderNumber}</strong><small>{new Date(o.createdAt).toLocaleString('pt-BR')}</small></div><strong>{money(o.total)}</strong></div><h3>{o.customer.name}</h3><p>{o.customer.phone} · {o.serviceType==='DELIVERY'?'Entrega':'Retirada'} · {o.items.reduce((s,i)=>s+i.quantity,0)} itens</p><label>Status<select value={o.status} onChange={e=>update(o.id,e.target.value)}>{statuses.map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></label></article>)}</section></main>}
