'use client';
import { FormEvent, useEffect, useState } from 'react';
import { API_URL, money } from '../../lib/api';
type Store = { id: string; name: string; slug: string };
type Category = { id: string; name: string; status: string };
type Product = { id: string; name: string; price: string; promotionalPrice?: string; status: string; category: { name: string } };
export default function AdminPage() {
  const [token, setToken] = useState(''); const [email, setEmail] = useState('admin@local.test'); const [password, setPassword] = useState('Admin@123456'); const [message, setMessage] = useState('');
  const [stores, setStores] = useState<Store[]>([]); const [storeId, setStoreId] = useState(''); const [categories, setCategories] = useState<Category[]>([]); const [products, setProducts] = useState<Product[]>([]);
  const [categoryName, setCategoryName] = useState(''); const [product, setProduct] = useState({ name: '', categoryId: '', price: '', promotionalPrice: '', description: '', imageUrl: '' });
  useEffect(() => { setToken(localStorage.getItem('menu-commerce-token') ?? ''); }, []);
  async function request(path: string, options: RequestInit = {}) { const r = await fetch(`${API_URL}${path}`, { ...options, headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}`, ...(options.headers ?? {}) } }); const data = await r.json(); if (!r.ok) throw new Error(Array.isArray(data.message) ? data.message.join(', ') : data.message ?? 'Erro na operação.'); return data; }
  async function login(e: FormEvent) { e.preventDefault(); try { const r = await fetch(`${API_URL}/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email, password }) }); const d = await r.json(); if (!r.ok) throw new Error(d.message); localStorage.setItem('menu-commerce-token', d.accessToken); setToken(d.accessToken); setMessage('Login realizado.'); } catch(e) { setMessage(e instanceof Error ? e.message : 'Erro.'); } }
  async function loadStores() { try { const data = await request('/admin/stores'); setStores(data); if (data[0]) { setStoreId(data[0].id); await loadCatalog(data[0].id); } } catch(e) { setMessage(e instanceof Error ? e.message : 'Erro.'); } }
  async function loadCatalog(id = storeId) { if (!id) return; const [c,p] = await Promise.all([request(`/admin/stores/${id}/categories`), request(`/admin/stores/${id}/products`)]); setCategories(c); setProducts(p); if (!product.categoryId && c[0]) setProduct(v => ({...v, categoryId:c[0].id})); }
  async function createCategory(e: FormEvent) { e.preventDefault(); await request('/admin/categories',{method:'POST',body:JSON.stringify({storeId,name:categoryName})}); setCategoryName(''); await loadCatalog(); }
  async function createProduct(e: FormEvent) { e.preventDefault(); await request('/admin/products',{method:'POST',body:JSON.stringify({storeId,...product,price:Number(product.price),promotionalPrice:product.promotionalPrice?Number(product.promotionalPrice):undefined})}); setProduct({name:'',categoryId:categories[0]?.id??'',price:'',promotionalPrice:'',description:'',imageUrl:''}); await loadCatalog(); }
  return <main className="admin-shell"><div className="admin-top"><div><span className="version">v0.4.1</span><h1>Painel administrativo</h1></div><div className="header-actions"><a href="/admin/pedidos">Pedidos</a><a href="/">Ver cardápio</a></div></div>
  {!token ? <section className="card"><h2>Entrar</h2><form onSubmit={login}><label>E-mail<input value={email} onChange={e=>setEmail(e.target.value)} type="email" /></label><label>Senha<input value={password} onChange={e=>setPassword(e.target.value)} type="password" /></label><button>Entrar</button></form></section> : <>
  <section className="card"><div className="toolbar"><h2>Loja</h2><button onClick={loadStores}>Carregar dados</button></div>{stores.length>0&&<select value={storeId} onChange={async e=>{setStoreId(e.target.value);await loadCatalog(e.target.value)}}>{stores.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select>}<p className="message">{message}</p></section>
  {storeId && <div className="admin-grid"><section className="card"><h2>Nova categoria</h2><form onSubmit={createCategory}><label>Nome<input value={categoryName} onChange={e=>setCategoryName(e.target.value)} required /></label><button>Cadastrar categoria</button></form><div className="list">{categories.map(c=><span key={c.id}>{c.name} · {c.status}</span>)}</div></section>
  <section className="card"><h2>Novo produto</h2><form onSubmit={createProduct}><label>Nome<input value={product.name} onChange={e=>setProduct({...product,name:e.target.value})} required /></label><label>Categoria<select value={product.categoryId} onChange={e=>setProduct({...product,categoryId:e.target.value})}>{categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Descrição<textarea value={product.description} onChange={e=>setProduct({...product,description:e.target.value})}/></label><div className="two"><label>Preço<input inputMode="decimal" value={product.price} onChange={e=>setProduct({...product,price:e.target.value})} required /></label><label>Promocional<input inputMode="decimal" value={product.promotionalPrice} onChange={e=>setProduct({...product,promotionalPrice:e.target.value})}/></label></div><label>URL da imagem<input value={product.imageUrl} onChange={e=>setProduct({...product,imageUrl:e.target.value})}/></label><button>Cadastrar produto</button></form></section></div>}
  {products.length>0&&<section className="card"><h2>Produtos cadastrados</h2><div className="table-wrap"><table><thead><tr><th>Produto</th><th>Categoria</th><th>Preço</th><th>Status</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td>{p.name}</td><td>{p.category.name}</td><td>{money(p.promotionalPrice??p.price)}</td><td>{p.status}</td></tr>)}</tbody></table></div></section>}
  </>}</main>;
}
