'use client';
import { useEffect, useState } from 'react';
import { API_URL, money } from '../../../lib/api';
type Order = { orderNumber:string; status:string; subtotal:string;deliveryFee:string;discount:string;couponCode?:string;total:string; serviceType:string; customer:{name:string}; items:{id:string;productNameSnapshot:string;quantity:number;totalPrice:string}[]; statusLog:{id:string;status:string;note?:string;createdAt:string}[] };
const labels:Record<string,string>={RECEIVED:'Recebido',CONFIRMED:'Confirmado',PREPARING:'Em preparação',READY:'Pronto',OUT_FOR_DELIVERY:'Saiu para entrega',DELIVERED:'Entregue',CANCELLED:'Cancelado'};
export default function OrderPage({params}:{params:Promise<{orderNumber:string}>}) {
 const [order,setOrder]=useState<Order|null>(null); const [error,setError]=useState('');
 useEffect(()=>{params.then(({orderNumber})=>fetch(`${API_URL}/orders/${orderNumber}`).then(async r=>{const d=await r.json();if(!r.ok||!d)throw new Error('Pedido não encontrado.');return d}).then(setOrder).catch(e=>setError(e.message)))},[params]);
 return <main className="admin-shell"><a href="/">← Cardápio</a><section className="card"><span className="version">Acompanhamento</span><h1>{order?`Pedido #${order.orderNumber}`:'Carregando pedido...'}</h1>{error&&<p className="error">{error}</p>}{order&&<><p>Cliente: {order.customer.name}</p><p>Status atual: <strong>{labels[order.status]??order.status}</strong></p><p>Atendimento: {order.serviceType==='DELIVERY'?'Entrega':'Retirada'}</p><div className="list">{order.items.map(i=><span key={i.id}>{i.quantity}× {i.productNameSnapshot} — {money(i.totalPrice)}</span>)}</div><div className="list"><span>Subtotal — {money(order.subtotal)}</span><span>Entrega — {money(order.deliveryFee)}</span>{Number(order.discount)>0&&<span>Desconto {order.couponCode?`(${order.couponCode})`:""} — - {money(order.discount)}</span>}</div><h2>Total: {money(order.total)}</h2><h3>Histórico</h3><div className="timeline">{order.statusLog.map(log=><div key={log.id}><strong>{labels[log.status]??log.status}</strong><small>{new Date(log.createdAt).toLocaleString('pt-BR')}{log.note?` · ${log.note}`:''}</small></div>)}</div></>}</section></main>;
}
